// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6bLiOF-YrldKtIgezFSLSM0TStUH2_74',
    appId: '1:369340637664:web:2f8abd5d949236ecc24b85',
    messagingSenderId: '369340637664',
    projectId: 'invite-earn-ac3c7',
    authDomain: 'invite-earn-ac3c7.firebaseapp.com',
    storageBucket: 'invite-earn-ac3c7.appspot.com',
    measurementId: 'G-5YF890ZX5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2crYY8ebDZE9JPGNHOb_y7dEYfc3ZUtQ',
    appId: '1:369340637664:android:28b0448290caf0c8c24b85',
    messagingSenderId: '369340637664',
    projectId: 'invite-earn-ac3c7',
    storageBucket: 'invite-earn-ac3c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADz8ZhHNVmRGGJ_E7cU4LcnQhCjcHkc8I',
    appId: '1:369340637664:ios:3fbf9673400b7791c24b85',
    messagingSenderId: '369340637664',
    projectId: 'invite-earn-ac3c7',
    storageBucket: 'invite-earn-ac3c7.appspot.com',
    iosBundleId: 'com.example.inviteEarn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADz8ZhHNVmRGGJ_E7cU4LcnQhCjcHkc8I',
    appId: '1:369340637664:ios:3fbf9673400b7791c24b85',
    messagingSenderId: '369340637664',
    projectId: 'invite-earn-ac3c7',
    storageBucket: 'invite-earn-ac3c7.appspot.com',
    iosBundleId: 'com.example.inviteEarn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6bLiOF-YrldKtIgezFSLSM0TStUH2_74',
    appId: '1:369340637664:web:777efe4d807112ecc24b85',
    messagingSenderId: '369340637664',
    projectId: 'invite-earn-ac3c7',
    authDomain: 'invite-earn-ac3c7.firebaseapp.com',
    storageBucket: 'invite-earn-ac3c7.appspot.com',
    measurementId: 'G-BFFRR714KW',
  );
}
